
sources += files(
    'ast_based_frontend.cc',
    'ast_based_frontend_with_parser.cc',
    'semantically_enabled_ast_based_frontend.cc',
    'semantically_enabled_ast_based_frontend_with_parser.cc',
    'single_ast_based_frontend.cc',
    'single_ast_based_frontend_with_parser.cc',
    'single_semantically_enabled_ast_based_frontend.cc',
    'single_semantically_enabled_ast_based_frontend_with_parser.cc',
)
