
#ifndef SOFTOMNILIB_TRAVERSAL_HH
#define SOFTOMNILIB_TRAVERSAL_HH

namespace SoftOmni::Parsing::Commons::AST::Base
{
    enum class Traversal
    {
        DEPTH_FIRST_SEARCH,
        DEPTH_FIRST_SEARCH_LAST_INDEX_COMES_FIRST,
        BREADTH_FIRST_SEARCH,
        BREADTH_FIRST_SEARCH_LAST_INDEX_COMES_FIRST,
        LINEAR_NO_RECURSE_INTO_CHILDREN,
        LINEAR_NO_RECURSE_INTO_CHILDREN_REVERSED_ORDER,
    };
}

#endif //SOFTOMNILIB_TRAVERSAL_HH
